### ISSUE TITLE
Logging proxy

### ISSUE THREAD

**Issue by lwolters** [elasticsoftwarefoundation/elasticactors#1]
We should use a proxy on an existing logging framework. Although this might not sound trivial, it is highly recommended since debugging actors is as cumbersome job.

When using a proxy, we might use e.g. threadlocal to log a particular request or actor / agent. This proxy is merely a proxy on java.util.logging

**Comment by andrebrait** [comment]
This has been addressed by migrating to SLF4J and the new logging options
